app/urls.py
from django.urls import path

from app import views
from covrel.views import covrel

app_name = 'app'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    # url(r'^.*\.html', views.gentella_html, name='gentella'),

    # The home page
    path('', views.index, name='index'),
    path('projects', views.list_projects, name='projects'),
    path('project/<int:id>', views.show_project, name='project'),
    path('features/<int:id>', views.list_features, name='features'),
    path('scenarios/<int:id>', views.list_scenarios, name='list_scenarios'),
    path('specs/<int:id>', views.list_specs, name='list_specs'),
    path('methods/<int:id>', views.list_methods, name='list_methods'),
    path('allmethods/<int:id>', views.all_methods, name='all_methods'),
    path('createproject', views.create_project),
    path('createmethods', views.create_methods),
    path('fullgraph/<int:id>', views.graph, name='full_graph'),
    path('specgraph/<int:id>', views.graph_specs, name='spec_graph'),
    path('graphfeatures/<int:id>', views.graph_features, name='graph'),
    path('graphmethods/<int:id>', views.graph_method, name='graph_method'),
    path('bublechart/<int:id>', views.bubble_chart, name='bubble'),
    path('insertprob/<int:id>', views.insert_probabilities, name='prob'),
    path('methodspecs/<int:id>', views.graph_method_specs, name='graph_spec_method'),

    # Probability
    path('probability/<int:id>', views.random_prob, name='random_prob')
]

gentelella/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app.urls', namespace='app')),
    path('covrel/', include('covrel.urls', namespace='covrel')),
]

app/templates/structure/base_site.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Gentelella Alela! | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "structure/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "structure/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "structure/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

app/templates/structure/fixed_footer.html
{% extends "structure/base_site.html" %}

{% block title %} Fixed Footer {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block body_class %}nav-md footer_fixed{% endblock body_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Footer <small> Just add class <strong>footer_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

app/templates/structure/fixed_sidebar.html
{% extends "structure/base_site.html" %}

{% block title %} Fixed Sidebar {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block sidebar_class %}nav-md menu_fixed{% endblock sidebar_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Sidebar <small> Just add class <strong>menu_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

app/templates/structure/footer.html
<div class="pull-right">
  SIMPLTON - Based on Template by <a href="https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/">Colorlib</a>
</div>
<div class="clearfix"></div>

app/templates/structure/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'app:index' %}" class="site_title"><i class="fa fa-spinner"></i> <span>Trace Feature</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
      <span>Welcome,</span>
      <h2>Rafael</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <!--<h3>General</h3>-->
      <ul class="nav side-menu">
        <li><a href="{% url 'app:index' %}"><i class="fa fa-home"></i> Home</a></li>
{#        <li><a href="{% url 'app:index' %}" class="fa fa-home">Home</a></li>#}
{#          <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="index.html">Dashboard</a></li>#}
{#            <li><a href="examples/index2.html">Dashboard2</a></li>#}
{#            <li><a href="examples/index3.html">Dashboard3</a></li>#}
{#          </ul>#}
{#        </li>#}
        <li><a href="{% url 'app:projects' %}"><i class="fa fa-laptop"></i> Projects </a></li>
{#        <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="form.html">General Form</a></li>#}
{#            <li><a href="form_advanced.html">Advanced Components</a></li>#}
{#            <li><a href="insert_prob.html">Form Validation</a></li>#}
{#            <li><a href="form_wizards.html">Form Wizard</a></li>#}
{#            <li><a href="form_upload.html">Form Upload</a></li>#}
{#            <li><a href="form_buttons.html">Form Buttons</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="">Inserir Probabilidades</a></li>#}
{#            <li><a href="examples/media_gallery.html">Media Gallery</a></li>#}
{#            <li><a href="examples/typography.html">Typography</a></li>#}
{#            <li><a href="examples/icons.html">Icons</a></li>#}
{#            <li><a href="examples/glyphicons.html">Glyphicons</a></li>#}
{#            <li><a href="examples/widgets.html">Widgets</a></li>#}
{#            <li><a href="examples/invoice.html">Invoice</a></li>#}
{#            <li><a href="inbox.html">Inbox</a></li>#}
{#            <li><a href="examples/calendar.html">Calendar</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="covrel_groups.html">Tables</a></li>#}
{#            <li><a href="features_list.html">Table Dynamic</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="examples/chartjs.html">Chart JS</a></li>#}
{#            <li><a href="examples/chartjs2.html">Chart JS2</a></li>#}
{#            <li><a href="examples/morisjs.html">Moris JS</a></li>#}
{#            <li><a href="examples/echarts.html">ECharts</a></li>#}
{#            <li><a href="examples/other_charts.html">Other Charts</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>#}
{#            <li><a href="fixed_footer.html">Fixed Footer</a></li>#}
{#          </ul>#}
{#        </li>#}
      </ul>
    </div>
{#    <div class="menu_section">#}
{#      <h3>Live On</h3>#}
{#      <ul class="nav side-menu">#}
{#        <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="examples/e_commerce.html">E-commerce</a></li>#}
{#            <li><a href="projects.html">Projects</a></li>#}
{#            <li><a href="project_detail.html">Project Detail</a></li>#}
{#            <li><a href="examples/contacts.html">Contacts</a></li>#}
{#            <li><a href="profile.html">Profile</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#            <li><a href="page_403.html">403 Error</a></li>#}
{#            <li><a href="page_404.html">404 Error</a></li>#}
{#            <li><a href="page_500.html">500 Error</a></li>#}
{#            <li><a href="examples/plain_page.html">Plain Page</a></li>#}
{#            <li><a href="login.html">Login Page</a></li>#}
{#            <li><a href="examples/pricing_tables.html">Pricing Tables</a></li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>#}
{#          <ul class="nav child_menu">#}
{#              <li><a href="#level1_1">Level One</a>#}
{#              <li><a>Level One<span class="fa fa-chevron-down"></span></a>#}
{#                <ul class="nav child_menu">#}
{#                  <li class="sub_menu"><a href="level2.html">Level Two</a>#}
{#                  </li>#}
{#                  <li><a href="#level2_1">Level Two</a>#}
{#                  </li>#}
{#                  <li><a href="#level2_2">Level Two</a>#}
{#                  </li>#}
{#                </ul>#}
{#              </li>#}
{#              <li><a href="#level1_2">Level One</a>#}
{#              </li>#}
{#          </ul>#}
{#        </li>#}
{#        <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>#}
{#      </ul>#}
{#    </div>#}
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="../examples/login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

app/templates/structure/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="/static/images/img.jpg" alt="">John Doe
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="javascript:;"> Profile</a></li>
          <li>
            <a href="javascript:;">
              <span class="badge bg-red pull-right">50%</span>
              <span>Settings</span>
            </a>
          </li>
          <li><a href="javascript:;">Help</a></li>
          <li><a href="../examples/login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-green">6</span>
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
          <li>
            <a>
              <span class="image"><img src="/static/images/img.jpg" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="/static/images/img.jpg" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="/static/images/img.jpg" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="/static/images/img.jpg" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <div class="text-center">
              <a>
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</div>