app/urls.py
from django.urls import path

from app import views
from covrel.views import covrel

app_name = 'app'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    # url(r'^.*\.html', views.gentella_html, name='gentella'),

    # The home page
    path('', views.index, name='index'),
    path('projects', views.list_projects, name='projects'),
    path('project/<int:id>', views.show_project, name='project'),
    path('features/<int:id>', views.list_features, name='features'),
    path('scenarios/<int:id>', views.list_scenarios, name='list_scenarios'),
    path('specs/<int:id>', views.list_specs, name='list_specs'),
    path('methods/<int:id>', views.list_methods, name='list_methods'),
    path('allmethods/<int:id>', views.all_methods, name='all_methods'),
    path('createproject', views.create_project),
    path('createmethods', views.create_methods),
    path('fullgraph/<int:id>', views.graph, name='full_graph'),
    path('specgraph/<int:id>', views.graph_specs, name='spec_graph'),
    path('graphfeatures/<int:id>', views.graph_features, name='graph'),
    path('graphmethods/<int:id>', views.graph_method, name='graph_method'),
    path('bublechart/<int:id>', views.bubble_chart, name='bubble'),
    path('insertprob/<int:id>', views.insert_probabilities, name='prob'),
    path('methodspecs/<int:id>', views.graph_method_specs, name='graph_spec_method'),

    # Probability
    path('probability/<int:id>', views.random_prob, name='random_prob')
]

gentelella/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('app.urls', namespace='app')),
    path('covrel/', include('covrel.urls', namespace='covrel')),
]

app/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Gentelella Alela! | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="/static/build/css/custom.css" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="/static/build/js/custom.js"></script>
    {% endblock body %}
  </body>
</html>

app/templates/bubble_chart.html
{% extends "structure/base_site.html" %}
{% load static %}
{% block title %} Projects {% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <style>
    text {
      font: 10px sans-serif;
    }
    </style>

{% endblock stylesheets %}

{% block content %}

    <script src="https://d3js.org/d3.v4.min.js"></script>
    <div class="block_graph" align="center">
        <h1>Features</h1>
{#        <svg width="1200" height="800" style="margin-left: 500px; margin-top: 100px;"></svg>#}

    </div>
    <script>

    var color_feature = d3.color("black");
    var color_border = d3.color("white");
    var color_scenario = d3.color("green");

    var diameter = 960,
    format = d3.format(",d"),
    color = d3.scaleOrdinal(d3.schemeCategory20c);

    var bubble = d3.pack()
        .size([diameter, diameter])
        .padding(1.5);

    var svg = d3.select("body").selectAll("div.block_graph")
            .append("svg")
            .attr("width", diameter)
            .attr("height", diameter)
            .attr("class", "bubble");

    d3.json("{% static 'data2.json' %}", function(error, data) {
      if (error) throw error;

      var root = d3.hierarchy(classes(data.nodes))
          .sum(function(d) { return d.value; })
          .sort(function(a, b) { return b.value - a.value; });

      bubble(root);
      var node = svg.selectAll(".node")
          .data(root.children)
        .enter().append("g")
          .attr("class", "node")
          .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

      node.append("title")
          .text(function(d) { return d.data.className + ": " + format(d.value); });

      node.append("circle")
          .attr("r", function(d) { return d.r; })
          .style("fill", function(d) {
            {#return color(d.data.packageName);#}
              if(d.data.packageName == 5){
                  return '#D2691E';
              }else if(d.data.packageName == 10){
                  return '#228B22';
              }else{
                  return color_border;
              }

          })
          .on("click", function(d) {
            get_children_graph(d.data.cod);
          });

      node.append("text")
          .attr("dy", ".3em")
          .style("text-anchor", "middle")
          .text(function(d) { return d.data.className.substring(0, d.r); });
    });


    function get_children_graph(id){
        {#alert('OLHAAAAAA ' +  id);#}
        const Http = new XMLHttpRequest();
        const url = '/graphfeatures';
        $(location).attr('href', url+'/'+ id);

    }

    // Returns a flattened hierarchy containing all leaf nodes under the root.
    function classes(root) {
      var classes = [];

      function recurse(name, node) {
          console.log(node.group);
        if (node.length > 0) node.forEach(function(child) { recurse(node.id, child); });
        else if (node.group != 15 && node.group != 10) classes.push({packageName: node.group, id: node.id, cod:node.cod, className: node.name, value: node.size});
      }

      recurse(null, root);
      return {children: classes};
    }

    d3.select(self.frameElement).style("height", diameter + "px");










        {#let color_feature = d3.color("black");#}
        {#let color_border = d3.color("white");#}
        {#let color_scenario = d3.color("green");#}
        {#let svg = d3.select("svg");#}
        {#let color = d3.scaleOrdinal(d3.schemeCategory20);#}
        {##}
        {#let circle = svg.append("circle")#}
        {#    .attr("cx", 200)#}
        {#    .attr("cy", 150)#}
        {#    .attr("r", 50)#}
        {#    .attr("fill", "red");#}
        {##}
        {#d3.json("{% static 'data2.json'%}", function(error, graph) {#}
        {#   if (error) throw error;#}
        {#    var bubbles = svg.append("g")#}
        {#        .attr("class", "bubble")#}
        {#        .selectAll("circle")#}
        {#    .data(graph.nodes)#}
        {#    .enter().append("circle")#}
        {#        .style("fill", function(d) {#}
        {#            return color(Math.random());#}
        {#        })#}
        {#        .style("stroke", function (d) {#}
        {#          if(d.group == 5){#}
        {#              return color_feature;#}
        {#          }else if(d.group == 10){#}
        {#              return color_scenario;#}
        {#          }else{#}
        {#              return color_border;#}
        {#          }#}
        {#        })#}
        {#    .style("stroke-width", function (d) {#}
        {#          if(d.group == 5){#}
        {#              return 3;#}
        {#          }else{#}
        {#              return 2;#}
        {#          }#}
        {#      })#}
        {#      .attr("r", function (d) {#}
        {#          if(d.group == 10){#}
        {#              return d.size*10;#}
        {#          }else{#}
        {#            return d.size*5;#}
        {#          }#}
        {#           })#}
        {#      .attr("fill", function(d) { return color(d.group); })#}
        {#        .attr("cx", function (d) { return d.size*30;})#}
        {#        .attr("cy", function (d) { return d.size*20;})#}




    </script>

{% endblock content %}

{% block javascripts %}
  {{ block.super }}

{% endblock javascripts %}

app/templates/cenarios_list.html
{% extends "structure/base_site.html" %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Scenarios <small>Feature: '<b>{{ feature }}</b>' </small></h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Features</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <p class="text-muted font-13 m-b-30">
                Below are all the Scenarios present in the Feature <b>'{{ feature }}</b>'.
              </p>
              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Line</th>
                    <th>Probability</th>
                    <th>Number of Methods</th>
                    <th>Methods</th>
                  </tr>
                </thead>
                <tbody>
                  {% for scenario in scenarios%}
                  <tr>
                    <td>{{ scenario.scenario_title }}</td>
                    <td>{{ scenario.line }}</td>
                    <td>{{ scenario.probability }}%</td>
                    <td>{{ scenario.executed_methods.all|length}}</td>
                    <td>
{#                        <thead>#}

{#                        </thead>#}
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>IF</th>
                                    <th>Probability</th>
                                    <th>Tests</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for method in scenario.executed_methods.all %}
                                    <tr>
                                        <td><a href="{% url 'app:graph_method' method.id %}">{{ method.method_name }}</a></td>
                                        <td><p>{{ method.impacted_features }}</p></td>
                                        <td><p>{{ method.probability }}%</p></td>
                                        <td><a href="{% url 'app:graph_spec_method' method.id %}">{{ method.number_of_tests }}</a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}

app/templates/features_list.html
{% extends "structure/base_site.html" %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Features <small>Extraídas dos arquivos .feature do projeto </small></h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Features</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <p class="text-muted font-13 m-b-30">
                Abaixo estão dispostas todas as Features implementadas no projeto em análise.
              </p>
              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Language</th>
                    <th>Scenarios</th>
                    <th>Probability</th>
                  </tr>
                </thead>


                <tbody>
                  {% for feature in features %}
                  <tr>
                    <td>{{ feature.feature_name }}</td>
                    <td>{{ feature.language }}</td>
                    <td><a href="{% url 'app:list_scenarios' feature.id %}">{{ feature.simple_scenarios.all|length }}</a></td>
                    <td>{{ feature.probability }}%</td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}

app/templates/fixed_footer.html
{% extends "base_site.html" %}

{% block title %} Fixed Footer {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block body_class %}nav-md footer_fixed{% endblock body_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Footer <small> Just add class <strong>footer_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

app/templates/specs_list.html
{% extends "structure/base_site.html" %}

{% block title %} Table Dynamic {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Specs</h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Features</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <p class="text-muted font-13 m-b-30">
                Below are all the Scenarios present in the Feature <b>'{{ feature }}</b>'.
              </p>
              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Line</th>
                    <th>File</th>
                    <th>Number of Methods</th>
                    <th>Methods</th>
                  </tr>
                </thead>
                <tbody>
                  {% for spec in specs%}
                  <tr>
                    <td>{{ spec.description}}</td>
                    <td>{{ spec.line }}</td>
                    <td>{{ spec.file }}</td>
                    <td>{{ spec.executed_methods.all|length}}</td>
                    <td>
{#                        <thead>#}

{#                        </thead>#}
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Probability</th>
                                    <th>Count Spectra</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for method in spec.executed_methods.all %}
                                    <tr>
                                        <td><a href="{% url 'app:graph_method' method.id %}">{{ method.method_name }}</a></td>
                                        <td><p>{{ method.get_probability }}%</p></td>
                                        <td><p>{{ method.get_count_spectra }}</p></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
  <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
  <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
  <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
  <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
  <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
  <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
  <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>
{% endblock javascripts %}